name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  release:
    types:
      - created

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if target branch is release/*
        id: check-branch
        run: |
          branch_name=$(echo ${{ github.event.release.tag_name }} | cut -d/ -f2)
          if [[ "$branch_name" =~ ^release\/.*$ ]]; then
            echo "Target branch is valid for deployment."
          else
            echo "Error: Invalid target branch. Deployment aborted."
            exit 1
          fi

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        if: success()
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        if: success()
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        if: success()
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
