name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  release:
    types:
      - created

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if target branch is release/*
        id: check-branch
        run: |
          if [[ "${{ github.event.release.target_commitish }}" =~ ^release/.*$ ]]; then
            echo "Target branch is valid for deployment: ${{ github.event.release.target_commitish }}."
          else
            echo "Error: Invalid target branch (${{ github.event.release.target_commitish }}). Deployment aborted."
            exit 1
          fi

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        if: success()
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        if: success()
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        if: success()
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
